spring:
  # DataSource Config
  datasource:
    write:
      url: jdbc:mysql://localhost:3306/base?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: base
      password: 1d1d100com
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      # filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      # 合并多个DruidDataSource的监控数据
      #spring.datasource.useGlobalDataSourceStat=true

    # 多数据源名称
    names: read,cemarose
    read:
      url: jdbc:mysql://47.93.38.144:3306/ms_common?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: ms_common
      password: DDweilai2018
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      # filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      # 合并多个DruidDataSource的监控数据
      #spring.datasource.useGlobalDataSourceStat=true
    cemarose:
      url: jdbc:mysql://47.93.38.144:3306/ms_common?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: ms_common
      password: DDweilai2018
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      # filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      # 合并多个DruidDataSource的监控数据
      #spring.datasource.useGlobalDataSourceStat=true
  redis:
    database: 2
    host: 127.0.0.1
    #password: # Login password of the redis server.
    port: 6379
    timeout: 0ms
#    jedis:
#      pool:
#        max-active: 8 #最大连接数
#        max-idle: 8 #最大空闲连接数
#        max-wait: -1ms #最大等待时间
#        min-idle: 0 #初始化连接数
  mail:
    host: xxx
    port: 25
    username: aaa@xxx.com
    password: xxx
    testConnection: false


server:
  port: 8089
  servlet:
    context-path: /base_api
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: X-Forwarded-Port
    accesslog:
      debug: true #请求响应数据调试
  use-forward-headers: true



frog:
  appkey: 58216558

