spring:
  application:
    name: Platform Service Provider
  profiles:
    active: @profileActive@
  aop:
      proxy-target-class: true
  jmx:
    enabled: false    #加入这个是避免fastdfs报错
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mybatis/*.xml

fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 118.190.154.251:22122

